import{describe,expect,it}from"vitest";import{extractEquipment,normalizeMessage,parseMessage,parseReport}from"../apps/api/src/services/operational-parser/index";
describe("parser operacional sem IA",()=>{
 it("normaliza acentos e espaços sem alterar o original",()=>{expect(normalizeMessage("  Correção   de SOLO ")).toBe("correcao de solo")});
 it.each([
  ["625 = rodando","625",[],"RODANDO","NORMAL"],["1531/830 = deslocamento para Chapadinha","1531",["830"],null,"DESLOCAMENTO"],["1530/2006 = atolada","1530",["2006"],null,"ATOLADO"],["1506/12016/12017 = deslocamento Chapadinha","1506",["12016","12017"],null,"DESLOCAMENTO"],["1602/1063 = aguardando área","1602",["1063"],null,"AGUARDANDO_AREA"],["1601 = disponível","1601",[],"DISPONIVEL",null],["1532/643 = dando apoio à irrigação","1532",["643"],null,"APOIO_OUTRA_OPERACAO"]
 ])("interpreta conjunto e situação: %s",(text,fleet,attachments,status,situation)=>{const p=parseMessage(text,{operation:"Plantio"});expect(p.mainEquipment).toBe(fleet);expect(p.attachments).toEqual(attachments);expect(p.proposedStatus).toBe(status);expect(p.operationalSituation).toBe(situation)});
 it("preserva conjunto sem dividir ocorrencias",()=>expect(extractEquipment("1506/12016/12017 = rodando")).toEqual({mainEquipment:"1506",attachments:["12016","12017"],equipmentSet:"1506/12016/12017"}));
 it("extrai quebra, previsão e baixa confiança sem inventar operação",()=>{const p=parseMessage("626 = cilindro de inclinação divisor de linha quebrado, previsão de liberação 18:00");expect(p.proposedStatus).toBe("PARADO");expect(new Date(p.forecastAt!).getHours()).toBe(18);expect(p.operation).toBeNull();expect(p.unresolvedFields).toContain("operation")});
 it.each([["Cultivo rodando no D1","Cultivo","D1"],["Correção de Solo rodou no J2","Correção de Solo","J2"],["Compostagem rodando na usina / transporte de torta","Compostagem","usina / transporte de torta"],["CPD aplicando pré-emergente no Ouro Verde 2 com frota 821","CPD","ouro verde 2"]])("classifica operação e local: %s",(text,operation,location)=>{const p=parseMessage(text);expect(p.operation).toBe(operation);expect(p.location).toBe(location)});
 it("mantem status anterior quando identifica só situação",()=>{const p=parseMessage("1604/100071 = aguardando área",{operation:"Cultivo"});expect(p.proposedStatus).toBeNull();expect(p.warnings[0]).toMatch(/manter estado anterior/)});
 it("separa relatório por operação e herda cabeçalho",()=>{const report=parseReport(`RELATÓRIO PLANTIO E COLHEITA DE MUDA\nData: 10/07/2026\nTurno: C\nVariedade: RB07-818\nPLANTIO\n1531/830 = deslocamento para Chapadinha\nCOLHEITA DE MUDA\n625 = rodando`);expect(report.items).toHaveLength(2);expect(report.items[0].operation).toBe("Plantio Mecanizado");expect(report.items[1].operation).toBe("Colheita de Muda");expect(report.items[1].variety).toBe("RB07-818")});
});
