import {describe,expect,it} from "vitest";
import {OperationalEngine} from "../apps/api/src/services/operational-engine";

const base={operation:"Plantio",fleet:"625",shift:"C",user:"Teste",responsible:"Teste",source:"SIMULATION" as const,approved:true,priority:"normal" as const};
describe("OperationalEngine append-only",()=>{
  it("cria eventos imutaveis sem operações de alteração ou exclusão",()=>{const engine=new OperationalEngine({simulationMode:true});const event=engine.append({...base,type:"STOPPED",newStatus:"PARADO"});expect(Object.isFrozen(event)).toBe(true);expect(engine.timeline()[0].id).toBe(event.id);expect(engine.all()).toHaveLength(1);expect((engine as unknown as Record<string,unknown>).update).toBeUndefined();expect((engine as unknown as Record<string,unknown>).delete).toBeUndefined()});
  it("calcula estado atual pelo ultimo evento confirmado",()=>{const engine=new OperationalEngine({simulationMode:true,seed:[{...base,type:"STOPPED",timestamp:"2026-07-11T20:00:00.000Z",newStatus:"PARADO"},{...base,type:"RETURNED",timestamp:"2026-07-11T20:20:00.000Z",newStatus:"RODANDO"}]});expect(engine.currentState("625")[0].status).toBe("RODANDO")});
  it("ignora evento nao aprovado na projecao",()=>{const engine=new OperationalEngine({simulationMode:true,seed:[{...base,type:"STATUS_CHANGED",newStatus:"RODANDO"},{...base,type:"STOPPED",newStatus:"PARADO",approved:false}]});expect(engine.currentState("625")[0].status).toBe("RODANDO")});
  it("calcula quantidade, maior parada e duracao",()=>{const engine=new OperationalEngine({simulationMode:true,seed:[{...base,type:"STOPPED",timestamp:"2026-07-11T20:00:00.000Z",newStatus:"PARADO"},{...base,type:"RETURNED",timestamp:"2026-07-11T20:25:00.000Z",newStatus:"RODANDO"}]});const metrics=engine.stopMetrics("625",new Date("2026-07-11T21:00:00.000Z"));expect(metrics.stopCount).toBe(1);expect(metrics.longestMinutes).toBe(25)});
  it("filtra timeline e gera diario do turno",()=>{const engine=new OperationalEngine({simulationMode:true,seed:[{...base,type:"SHIFT_STARTED",observation:"Início"},{...base,type:"WARNING",fleet:"626",observation:"Aviso"}]});expect(engine.timeline({fleet:"626"})).toHaveLength(1);expect(engine.shiftJournal("C")).toHaveLength(2)});
  it("pesquisa estado, eventos e historico juntos",()=>{const engine=new OperationalEngine({simulationMode:true,seed:[{...base,type:"STOPPED",newStatus:"PARADO",newDescription:"Bico injetor"}]});const result=engine.search("bico");expect(result.currentState[0].fleet).toBe("625");expect(result.histories[0].events).toHaveLength(1)});
  it("prepara comandos sem executar Excel ou WhatsApp",()=>{const engine=new OperationalEngine({simulationMode:true});const event=engine.append({...base,type:"STATUS_CHANGED",newStatus:"PARADO"});expect(engine.toExcelCommands(event)[0].execute).toBe(false);expect(engine.toWhatsAppCommands(event)[0]).toMatchObject({execute:false,reaction:null})});
  it("recusa motor real sem adaptadores homologados",()=>{expect(()=>new OperationalEngine({simulationMode:false})).toThrow(/homologados/)});
});
