import{randomUUID}from"node:crypto";import{OperationalEngine,rebuildProjections}from"./operational-engine.js";import{parseMessage,parseReport,ParsedOperationalMessage}from"./operational-parser/index.js";import{MemoryMessageRepository,MemoryPendingRepository,MemoryProjectionRepository,MemoryReportRepository,MessageRepository,OperationalPending,PendingRepository,ProjectionRepository,ReportRepository,SimulatedMessage}from"../repositories/operational-contracts.js";
export class OperationalWorkflow{
  readonly messages:MessageRepository;readonly pendings:PendingRepository;readonly projections:ProjectionRepository<ReturnType<typeof rebuildProjections>>;readonly reports:ReportRepository;
  constructor(readonly engine:OperationalEngine,repositories:{messages?:MessageRepository;pendings?:PendingRepository;projections?:ProjectionRepository<ReturnType<typeof rebuildProjections>>;reports?:ReportRepository}={}){this.messages=repositories.messages??new MemoryMessageRepository();this.pendings=repositories.pendings??new MemoryPendingRepository();this.projections=repositories.projections??new MemoryProjectionRepository<ReturnType<typeof rebuildProjections>>();this.reports=repositories.reports??new MemoryReportRepository();}
  parse(text:string,context:Record<string,string|null|undefined>={}){return text.split(/\r?\n/).filter(line=>/^\d{3,6}(?:\/\d{3,6})*\s*=/.test(line.trim())).length>1?parseReport(text):parseMessage(text,context)}
  simulate(input:{idempotencyKey:string;group:string;sender:string;receivedAt?:string;shift:string;text:string}){if(this.messages.findByKey(input.idempotencyKey))throw new WorkflowError(409,"Mensagem duplicada.");const parsed=this.parse(input.text,{shift:input.shift});const interpretations="items"in parsed?parsed.items:[parsed];const message:SimulatedMessage={id:randomUUID(),...input,receivedAt:input.receivedAt??new Date().toISOString(),interpretations,status:"PARSED"};this.messages.save(message);this.engine.append({type:"MESSAGE_RECEIVED",source:"SIMULATION",originalMessage:input.text,group:input.group,shift:input.shift,user:input.sender,responsible:input.sender,approved:true,priority:"normal",observation:"Mensagem simulada recebida"});return message}
  createPendings(messageId:string){const message=this.requiredMessage(messageId);const created:OperationalPending[]=[];for(const interpretation of message.interpretations){if(!interpretation.mainEquipment)continue;const state=this.engine.currentState(interpretation.mainEquipment)[0];const changed=this.changed(state,interpretation);const doubt=interpretation.unresolvedFields.length>0||(!interpretation.proposedStatus&&Boolean(interpretation.operationalSituation));if(!changed&&!doubt)continue;if(this.pendings.list().some(p=>p.status==="OPEN"&&p.interpretation.originalText===interpretation.originalText))continue;const pending:OperationalPending={id:randomUUID(),messageId,interpretation:{...interpretation,currentStatus:(state?.status as ParsedOperationalMessage["currentStatus"])??null},baselineStatus:state?.status??null,baselineDescription:state?.description??null,baselineSector:state?.sector??null,status:"OPEN",reason:doubt?"DOUBT":"CHANGE",createdAt:new Date().toISOString()};this.pendings.save(pending);this.engine.append({type:"PENDING_CREATED",fleet:interpretation.mainEquipment,implement:interpretation.attachments.join("/"),operation:interpretation.operation??undefined,source:"SIMULATION",originalMessage:interpretation.originalText,shift:interpretation.shift??message.shift,user:message.sender,responsible:message.sender,approved:false,priority:interpretation.confidence<.6?"urgent":"normal",newStatus:interpretation.proposedStatus??undefined,newDescription:interpretation.description??undefined,newSector:interpretation.location??undefined,observation:doubt?"Revisão necessária":"Mudança identificada"});created.push(pending)}message.status=created.length?"PENDING":"PROCESSED";this.messages.save(message);return created}
  approve(id:string,responsible:string){const pending=this.requiredPending(id);const fleet=pending.interpretation.mainEquipment!;const current=this.engine.currentState(fleet)[0];if((current?.status??null)!==pending.baselineStatus||(current?.description??null)!==pending.baselineDescription)throw new WorkflowError(409,"Conflito: estado atual mudou após a criação da pendência.");const proposed=pending.interpretation.proposedStatus;const type=proposed==="PARADO"?"STOPPED":pending.baselineStatus==="PARADO"&&proposed==="RODANDO"?"RETURNED":"STATUS_CHANGED";const event=this.engine.append({type,fleet,implement:pending.interpretation.attachments.join("/"),operation:pending.interpretation.operation??current?.operation,previousStatus:pending.baselineStatus??undefined,newStatus:proposed??pending.baselineStatus??undefined,previousDescription:pending.baselineDescription??undefined,newDescription:pending.interpretation.description??undefined,previousSector:pending.baselineSector??undefined,newSector:pending.interpretation.location??undefined,source:"PANEL",originalMessage:pending.interpretation.originalText,shift:pending.interpretation.shift??"C",user:responsible,responsible,approved:true,priority:"normal",observation:`Situação: ${pending.interpretation.operationalSituation??"NORMAL"}`});pending.status="APPROVED";pending.resolvedAt=new Date().toISOString();this.pendings.save(pending);this.rebuild();return{event,excelCommands:this.engine.toExcelCommands(event),whatsAppCommands:this.engine.toWhatsAppCommands(event),externalActionExecuted:false}}
  reject(id:string,responsible:string,reason="Rejeitada pelo operador"){const pending=this.requiredPending(id);pending.status="REJECTED";pending.resolvedAt=new Date().toISOString();this.pendings.save(pending);const event=this.engine.append({type:"CONFIRMED",fleet:pending.interpretation.mainEquipment??undefined,operation:pending.interpretation.operation??undefined,source:"PANEL",originalMessage:pending.interpretation.originalText,user:responsible,responsible,approved:true,priority:"normal",observation:`Pendência rejeitada: ${reason}`});return{event,externalActionExecuted:false}}
  rebuild(){const result=rebuildProjections(this.engine.all());this.projections.clear();this.projections.replace(result);return result}
  shiftDraft(){const confirmed=this.engine.currentState();const open=this.pendings.list().filter(p=>p.status==="OPEN");const lines=["*📋 RELATÓRIO DE TROCA DE TURNO*","",...confirmed.map(x=>`• ${x.fleet} — ${x.status}: ${x.description}`),"","⚠️ *PENDÊNCIAS NÃO CONFIRMADAS*",...(open.length?open.map(p=>`• ${p.interpretation.equipmentSet}: ${p.interpretation.description}`):["• Nenhuma"])];const text=lines.join("\n");this.reports.saveDraft(text);return{text,confirmedEvents:this.engine.shiftJournal("C"),openPendings:open,simulated:true}}
  private changed(state:ReturnType<OperationalEngine["currentState"]>[number]|undefined,p:ParsedOperationalMessage){if(!state)return true;return Boolean(p.proposedStatus&&p.proposedStatus!==state.status||p.description&&p.description!==state.description||p.location&&p.location!==state.sector)}
  private requiredMessage(id:string){const x=this.messages.find(id);if(!x)throw new WorkflowError(404,"Mensagem não encontrada.");return x}private requiredPending(id:string){const x=this.pendings.find(id);if(!x)throw new WorkflowError(404,"Pendência não encontrada.");if(x.status!=="OPEN")throw new WorkflowError(409,"Pendência já resolvida.");return x}
}
export class WorkflowError extends Error{constructor(readonly status:number,message:string){super(message)}}
